export const storyData = [
  {
    id: 1,
    src: "https://framerusercontent.com/modules/7Jaowzn7eq0jiSSqshsw/81bTmQsUaRXxwdFASHjQ/assets/2048/e1Z6aqN1zviwdY6BNNR8MQ5lM.jpg",
    storyName: "Mountain",
    fullName: "Enchanted Forest Path",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    story: {
      p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
      p2: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
      p3: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      p4: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
      p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 2,
    src: "https://framerusercontent.com/images/6QtmtICiTmr01Nk0lIdKYXC0fc.jpg?scale-down-to=2048",
    storyName: "Forest",
    fullName: "Majestic Mountain Sunrise",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    story: {
      p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
      p2: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
      p3: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      p4: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
      p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 3,
    src: "https://framerusercontent.com/images/FXN7aLDuqfCGBCdTrisNZiQHsDY.jpg?scale-down-to=2048",
    storyName: "Water",
    fullName: "Graceful Wildlife Encounter",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    story: {
      p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
      p2: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
      p3: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      p4: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
      p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 4,
    src: "https://framerusercontent.com/images/7SZM6o6KIrwEDNf65gPXokbliiM.jpg?scale-down-to=2048",
    storyName: "Urban Jungle",
    fullName: "Rural Life in the Frame",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    story: {
      p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
      p2: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
      p3: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      p4: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
      p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 5,
    src: "https://framerusercontent.com/images/57VsVVaztJjK6epEym90CCsrpd0.jpg?scale-down-to=2048",
    storyName: "Rural Life",
    fullName: "The Dance of Light and Water",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    story: {
      p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
      p2: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
      p3: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      p4: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
      p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 6,
    src: "https://framerusercontent.com/images/ce7pXAjq2vFWCs3tvuwdhlI0U.jpg?scale-down-to=2048",
    storyName: "Wild Life",
    fullName: "Urban Jungle Reflections",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    story: {
      p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
      p2: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
      p3: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      p4: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
      p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
];
