export const storyData = [
  {
    id: 1,
    src: "https://framerusercontent.com/modules/7Jaowzn7eq0jiSSqshsw/81bTmQsUaRXxwdFASHjQ/assets/2048/e1Z6aqN1zviwdY6BNNR8MQ5lM.jpg",
    storyName: "Mountain",
    fullName: "Enchanted Forest Path",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    stories: {
      story1: {
        p1: "There's a certain magic that can only be found within the depths of an ancient forest. The air is thick with the scent of earth and moss, the trees reach toward the heavens, and the ground is carpeted with a lush tapestry of ferns and wildflowers. It's a world where time seems to stand still, and as a photographer, it's a world I'm constantly drawn to explore. Join me on a journey through the Enchanted Forest Path, where the play of light and shadow creates a world of wonder.",
        p2: "The Path Less Traveled: A Hidden World Beckons",
        p3: "The Enchanted Forest Path is not one that you'll find on most maps. It's a hidden gem, known only to those who are willing to venture off the beaten track. As you step onto the path, you leave behind the noise and chaos of the outside world and enter a realm of quiet contemplation.",
        p4: "The towering trees that line the path create a natural cathedral, their branches forming a canopy that filters the sunlight into dappled patterns on the forest floor. It's a world where every step feels like a journey deeper into the heart of nature itself.",
        p5: "Capturing the Play of Light and Shadow",
        p6: "One of the most enchanting aspects of the forest is the way light and shadow dance together. As the sun filters through the leaves above, it creates a constantly shifting tableau of shapes and colors. For a photographer, it's a challenge and a delight to capture this play of light and shadow.",
        p7: "Using a combination of exposure techniques and creative framing, I aim to convey the sense of depth and mystery that permeates the forest. Close-up shots of sun-dappled leaves, wide-angle views of the towering trees, and intimate portraits of the forest's inhabitants all have their place in telling the story of this enchanted world.",
      },
      story2: {
        p1: "The Inhabitants of the Enchanted Forest",
        p2: "Speaking of inhabitants, the forest is teeming with life. Squirrels scurry up tree trunks, birds call from the branches above, and if you're lucky, you might catch a glimpse of a deer or a fox darting through the underbrush.",
        p3: "For a photographer, these moments are pure gold. The challenge lies in being patient and unobtrusive, allowing the forest's residents to go about their business without disturbance. And when that magical moment comes—a fox pausing in a sunbeam or a bird taking flight—it's a testament to the serendipity of nature photography.",
        p4: "Nature's Magic Awaits ",
        p5: "The Enchanted Forest Path is more than just a place; it's an experience. It's a reminder that there are pockets of magic in the world, waiting to be discovered by those who are willing to seek them out. As a photographer, I'm fortunate to have the opportunity to capture and share these moments of enchantment with others.",
        p6: "So, the next time you find yourself in the presence of an ancient forest, take a moment to step off the path and explore. You never know what wonders might await you in the dappled light and quiet shadows. As a photographer, I can assure you that the Enchanted Forest Path is a world worth discovering.",
      },
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 2,
    src: "https://framerusercontent.com/images/6QtmtICiTmr01Nk0lIdKYXC0fc.jpg?scale-down-to=2048",
    storyName: "Forest",
    fullName: "Majestic Mountain Sunrise",
    date: "Sep 28,2023",
    header1: "The Call of Dawn: Preparation and Patience",
    header2: "A Palette of Colors: Capturing the Moment ",
    header3: "The Afterglow: Reflection and Contemplation ",
    header4: "A Snapshot of Eternity",
    stories: {
      story1: {
        p1: "The mountains have always held a special allure for photographers and nature enthusiasts alike. Their grandeur, their timelessness, and their ability to humble us in the face of their towering peaks are just a few reasons why they make such compelling subjects for photography. Among the many moments a mountain can offer, there's one that stands out as truly magical—the sunrise.In the darkness before dawn, when most of the world is still asleep, there's a transformation taking place. It's a moment when the world awakens to a new day, and as a photographer, capturing that moment is both a challenge and a privilege. Join me on a journey to the heart of the mountains as we explore the challenges and rewards of capturing the majestic beauty of a mountain sunrise.",
        p2: "The Call of Dawn: Preparation and Patience ",
        p3: "Before embarking on the quest to capture a mountain sunrise, preparation is key. It starts with researching the location and knowing the best vantage points. Mountains are known for their unpredictable weather, so checking the forecast is essential. Layering up and packing essential gear, including a sturdy tripod and a selection of lenses, is crucial.",
        p4: "However, even the most prepared photographer knows that the mountain dictates the terms. Sunrise can be a fleeting moment, so you must be prepared to wait. And wait. And wait. It's in these moments of quiet anticipation that the magic happens. As the first light of dawn begins to paint the sky, you'll feel a surge of excitement that makes the early wake-up call and the chilly temperatures entirely worthwhile.",
        p5: "A Palette of Colors: Capturing the Moment ",
        p6: "As the sun starts to breach the horizon, the mountains come to life in an array of colors. The sky may ignite with shades of pink, orange, and purple, while the mountains themselves transition from muted grays to warm tones of gold and amber. It's a spectacle that no camera can fully do justice, but that doesn't stop us from trying.",
        p7: "Using a combination of exposure settings, filters, and creative framing, we strive to capture the essence of the moment. Long exposures may be used to smooth out the motion of clouds, or telephoto lenses may be employed to emphasize distant peaks. The choice of how to capture this moment is as unique as the photographer themselves.",
      },
      story2: {
        p1: "The Afterglow: Reflection and Contemplation",
        p2: "Once the sun has risen, many photographers pack up and call it a day. But the true beauty of a mountain sunrise often lingers in the moments that follow. As the day awakens, the mountains are bathed in a soft, diffused light that reveals intricate details and textures. This is the time to switch to a different lens and explore the landscape in a new way.",
        p3: "It's also a time for reflection—both literally and metaphorically. The mirror-like surfaces of mountain lakes can offer stunning reflections of the peaks, creating a sense of symmetry and tranquility. And as you stand there, in the midst of this natural wonder, you can't help but reflect on the beauty and majesty of the world.",
        p4: "A Snapshot of Eternity",
        p5: "Capturing a majestic mountain sunrise is a bit like freezing a moment of eternity. It's a reminder that, in the grand scheme of things, our time on this planet is fleeting, but the mountains endure. As photographers, we're fortunate to have the opportunity to witness and share these moments, and with each click of the shutter, we become a part of the mountains' timeless story.",
        p6: "So, the next time you find yourself in the shadow of a mountain at dawn, remember that you're not just taking a photograph; you're capturing a piece of eternity, a slice of the Earth's history, and a testament to the enduring beauty of the natural world.",
      },
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/F4Y8yGsDnEqlhdp6Tc6eo5WU15Q.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/KcJyW0rSctyTPtaLzeEegUqVug.jpg?scale-down-to=2048",
    },
  },
  {
    id: 3,
    src: "https://framerusercontent.com/images/FXN7aLDuqfCGBCdTrisNZiQHsDY.jpg?scale-down-to=2048",
    storyName: "Water",
    fullName: "Graceful Wildlife Encounter",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    stories: {
      story1: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
      story2: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 4,
    src: "https://framerusercontent.com/images/7SZM6o6KIrwEDNf65gPXokbliiM.jpg?scale-down-to=2048",
    storyName: "Urban Jungle",
    fullName: "Rural Life in the Frame",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    stories: {
      story1: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
      story2: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 5,
    src: "https://framerusercontent.com/images/57VsVVaztJjK6epEym90CCsrpd0.jpg?scale-down-to=2048",
    storyName: "Rural Life",
    fullName: "The Dance of Light and Water",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    stories: {
      story1: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
      story2: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
  {
    id: 6,
    src: "https://framerusercontent.com/images/ce7pXAjq2vFWCs3tvuwdhlI0U.jpg?scale-down-to=2048",
    storyName: "Wild Life",
    fullName: "Urban Jungle Reflections",
    date: "Sep 28,2023",
    header1: "The Path Less Traveled: A Hidden World Beckons",
    header2: "The Path Less Traveled: A Hidden World Beckons",
    header3: "The Path Less Traveled: A Hidden World Beckons",
    header4: "The Path Less Traveled: A Hidden World Beckons",
    stories: {
      story1: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
      story2: {
        p1: "",
        p2: "",
        p3: "",
        p4: "",
        p5: "",
        p6: "",
      },
    },
    storyImgSrc: {
      src1: "https://framerusercontent.com/images/BbRbMCo1r8FOW4cCv3GUajuxAh4.jpg?scale-down-to=2048",
      src2: "https://framerusercontent.com/images/0kyckfmmGgjHFHuII4Vk1Zrf7E.jpg?scale-down-to=2048",
    },
  },
];
